cc_library(
    name = 'dag_creator',
    deps = [
           '//util/segmenter/internal:dag_creator_internal',
           ],
)

cc_library(
    name = 'razor_wind',
    deps = [
           '//util/segmenter/internal:razor_wind_internal',
           ],
)

cc_library(
    name = 'bems_emit_matrix',
    deps = [
           '//util/segmenter/internal:bems_emit_matrix_internal',
           ],
)

cc_library(
    name = 'hidden_markov_model',
    deps = [
           '//util/segmenter/internal:hidden_markov_model_internal',
           ],
)

cc_library(
    name = 'state_trans_matrix',
    deps = [
           '//util/segmenter/internal:state_trans_matrix_internal',
           ],
)

cc_library(
    name = 'start_prob_matrix',
    deps = [
           '//util/segmenter/internal:start_prob_matrix_internal',
           ],
)

cc_library(
    name = 'punct_filter',
    deps = [
           '//util/segmenter/internal:punct_filter_internal',
           ],
)
