# Copyright 2013 Makepolo Inc. All Rights Reserved.
# Author: huangyue@makepolo.com (Yue Huang)

cc_library(
    name = 'spliter_for_utf8_internal',
    srcs = [
           'spliter_for_utf8.cc',
           ],
    deps = [
           '//base:base',
           '//util/registrant/public:registrant',
           ],
    link_all_symbols=True
)

cc_library(
    name = 'spliter_for_gbk_internal',
    srcs = [
           'spliter_for_gbk.cc',
           ],
    deps = [
           '//base:base',
           '//util/registrant/public:registrant',
           ],
    link_all_symbols=True
)
